{% set name = "stackvana-core" %}
# LSST DM versions are prefixed with letters
#
#  - a weekly build is 'w_2018_50'
#  - a major release is 'v18_1'
#
# In order to play nice with conda, we take the following conventions
#
#  - for a weekly build 'w_2018_50', the conda version is '0.2018.50'
#  - for a major version 'v18_1', the conda version is '18.1.0'
#
{% set version = "0.2024.3" %}
{% set patch_version = version.split(".")[-1] if version.split(".")[-1].__len__() == 2 else "0" + version.split(".")[-1] %}
{% set dm_tag = "w_" + version.split(".")[1] + "_" + patch_version if version.startswith("0.") else "v" + version.replace(".", "_") %}

{% set rubin_env = "8" %}
{% set lsst_pyver = "3.11" %}
{% set skip_pyver = lsst_pyver.replace(".", "") | int %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://eups.lsst.codes/stack/src/tags/{{ dm_tag }}.list
  sha256: 56fc79e6eccce892991d9062ef9c7498e6e4faf07bc82a996f4885fc92d48c75

build:
  {% if win or py != skip_pyver %}
  skip: true
  {% endif %}
  number: 0
  merge_build_host: true
  script_env:
    - LSST_PYVER={{ lsst_pyver }}

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: stackvana-core
    version: {{ version }}
    run_exports:
      - {{ pin_subpackage('stackvana-core-impl', exact=True) }}
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('stackvana-core-impl', exact=True) }}
    test:
      commands:
        - eups -h
        - eups list
        - if [[ ! ${STACKVANA_ACTIVATED} ]]; then exit 1; fi

  - name: stackvana-core-impl
    version: {{ version }}
    script: build_impl.sh
    requirements:
      host:
        - python
        - rubin-env-nosysroot ={{ rubin_env }}
      run:
        - python
        - {{ pin_compatible('rubin-env-nosysroot', max_pin='x') }}
    test:
      script: run_test_impl.sh
      requires:
        - python
        - rubin-env-nosysroot ={{ rubin_env }}

about:
  home: https://github.com/beckermr/stackvana-core
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - LICENSE
    - COPYRIGHT
  summary: core build tooling for stackvana

extra:
  recipe-maintainers:
    - beckermr
