{% set name = "stackvana-core" %}
# LSST DM versions are prefixed with letters
#
#  - a weekly build is 'w_2018_50'
#  - a major release is 'v18_1'
#
# In order to play nice with conda, we take the following conventions
#
#  - for a weekly build 'w_2018_50', the conda version is '0.2018.50'
#  - for a major version 'v18_1', the conda version is '18.1.0'
#
{% set version = "0.2022.18" %}
{% set patch_version = version.split(".")[-1] if version.split(".")[-1].__len__() == 2 else "0" + version.split(".")[-1] %}
{% set dm_tag = "w_" + version.split(".")[1] + "_" + patch_version if version.startswith("0.") else "v" + version.replace(".", "_") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://eups.lsst.codes/stack/src/tags/{{ dm_tag }}.list
  sha256: 3bc18cbc77e03a9365ae72b58ce95b60ce19c061f53744c40886b17df813b76f

build:
  skip: true  # [win or py != 38]
  number: 0
  merge_build_host: true

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: stackvana-core
    version: {{ version }}
    run_exports:
      - {{ pin_subpackage('stackvana-core-impl', exact=True) }}
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('stackvana-core-impl', exact=True) }}
    test:
      commands:
        - eups -h
        - eups list
        - if [[ ! ${STACKVANA_ACTIVATED} ]]; then exit 1; fi

  - name: stackvana-core-impl
    version: {{ version }}
    script: build_impl.sh
    requirements:
      host:
        - python
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - rubin-env-nosysroot >=3
      run:
        - python
        - {{ pin_compatible('rubin-env-nosysroot', max_pin='x') }}
    test:
      script: run_test_impl.sh
      requires:
        - python
        - rubin-env-nosysroot >=3
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}

about:
  home: https://github.com/beckermr/stackvana-core
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - LICENSE
    - COPYRIGHT
  summary: core build tooling for stackvana

extra:
  recipe-maintainers:
    - beckermr
