# LSST DM versions are prefixed with letters
#
#  - a weekly build is 'w_2018_50'
#  - a major release is 'v18_1'
#
# In order to play nice with conda, we take the following conventions
#
#  - for a weekly build 'w_2018_50', the conda version is '0.2018.50'
#  - for a major version 'v18_1', the conda version is '18.1.0'
#
context:
  name: stackvana-core
  version: 0.2025.40

  patch_version: 40  # $ version | split(".")[-1] if version | split(".")[-1]|length == 2 else "0" + version.split(".")[-1] }}
  dm_tag: w_2025_40 # $ "w_" + version.split(".")[1] + "_" + patch_version if version.startswith("0.") else "v" + version.replace(".", "_") }}

recipe:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://eups.lsst.codes/stack/src/tags/${{ dm_tag }}.list
  sha256: 0dc3553cde005ead150677f51170511b2dedb44a44d62ca00ffa5ef728698cf3

build:
  skip:
    - win
    - match(python, "!=${{ lsst_pyver }}")
  number: 0
  merge_build_and_host_envs: true

outputs:
  - package:
      name: stackvana-core

    requirements:
      host:
        - python
      run:
        - python
        - ${{ pin_subpackage('stackvana-core-impl', exact=True) }}
      run_exports:
        - ${{ pin_subpackage('stackvana-core-impl', exact=True) }}

    tests:
      - script:
          - eups -h
          - eups list
          - if [[ ! ${STACKVANA_ACTIVATED} ]]; then exit 1; fi

  - package:
      name: stackvana-core-impl

    build:
      script:
        file: build_impl.sh
        env:
          LSST_PYVER: ${{ lsst_pyver }}

    requirements:
      host:
        - python
        - rubin-env-nosysroot =${{ rubin_env }}
      run:
        - python
        - ${{ pin_compatible('rubin-env-nosysroot', upper_bound='x') }}

    tests:
      - script: run_test_impl.sh
        requirements:
          run:
            - python
            - rubin-env-nosysroot =${{ rubin_env }}

about:
  homepage: https://github.com/beckermr/stackvana-core
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - COPYRIGHT
  summary: core build tooling for stackvana

extra:
  recipe-maintainers:
    - beckermr
